import { library } from "@fortawesome/fontawesome-svg-core";
// Import the specific icons you need from the solid pack
import {
  faEye,
  faEdit,
  faSun,
  faMoon,
  faCog,
  faQuestion,
  faTimes,
  faInfoCircle,
  faLanguage,
  faCheckCircle,
  faExclamationCircle,
  faExclamationTriangle,
  faSpinner,
  faSync,
  faExchangeAlt,
  faCheck,
  faSave,
  faUndo,
  faCloudUploadAlt,
  faCloudDownloadAlt,
  faCloudDownload,
  faArchive,
  faCloud,
  faFileAlt,
  faPalette,
  faTrash,
  faFile,
  faFolder,
  faDownload,
  // New icons for ChatGPT integration
  faPaperPlane,
  faFileImport,
  faRobot,
  faBrain,
  faMagic,
} from "@fortawesome/free-solid-svg-icons";

// Add all icons to the library
library.add(
  faEye,
  faEdit,
  faSun,
  faMoon,
  faCog,
  faQuestion,
  faTimes,
  faInfoCircle,
  faLanguage,
  faCheckCircle,
  faExclamationCircle,
  faExclamationTriangle,
  faSpinner,
  faSync,
  faExchangeAlt,
  faCheck,
  faSave,
  faUndo,
  faCloudUploadAlt,
  faCloudDownloadAlt,
  faCloudDownload,
  faArchive,
  faCloud,
  faFileAlt,
  faPalette,
  faTrash,
  faFile,
  faFolder,
  faDownload,
  // New icons for ChatGPT integration
  faPaperPlane,
  faFileImport,
  faRobot,
  faBrain,
  faMagic
);
