export const shortcuts = [
    { key: "Ctrl+1-7", action: "Switch to tab 1-7" },
    { key: "Ctrl+e", action: "Toggle edit/preview mode" },
    { key: "Ctrl+d", action: "Toggle dark/light theme" },
    { key: "Ctrl+b", action: "Bold text" },
    { key: "Ctrl+i", action: "Italic text" },
    { key: "Ctrl+t", action: "Insert timestamp" },
    { key: "Ctrl+l", action: "Unordered List" },
    { key: "Ctrl+o", action: "Ordered List" },
    { key: "Ctrl+h", action: "Insert Link" },
    { key: "Tab", action: "Insert indentation" },
    { key: "Shift+Tab", action: "Remove indentation" },
    { key: "Ctrl+z", action: "Undo" },
    { key: "Ctrl+y", action: "Redo" },
    { key: "Ctrl+Shift+J", action: "Hide/Show Window" },
    { key: "Ctrl+Shift+G", action: "Chat with AI"},
    { key: "Ctrl+Shift+S", action: "Summarize with AI"},
    { key: "Ctrl+Shift+B", action: "Create backup"},
  ];